//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFrontend.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFrontend.Resources.Files.RestResources", typeof(RestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services/categories/.
        /// </summary>
        internal static string CategoriesURL {
            get {
                return ResourceManager.GetString("CategoriesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clients/.
        /// </summary>
        internal static string ClientsURL {
            get {
                return ResourceManager.GetString("ClientsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments/.
        /// </summary>
        internal static string CommentsURL {
            get {
                return ResourceManager.GetString("CommentsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companies/.
        /// </summary>
        internal static string CompaniesURL {
            get {
                return ResourceManager.GetString("CompaniesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services/details/.
        /// </summary>
        internal static string CompanyDetailsURL {
            get {
                return ResourceManager.GetString("CompanyDetailsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company/.
        /// </summary>
        internal static string CompanyURL {
            get {
                return ResourceManager.GetString("CompanyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.1.39:9000/api/.
        /// </summary>
        internal static string ConnectionURL {
            get {
                return ResourceManager.GetString("ConnectionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add/.
        /// </summary>
        internal static string CreateAccountURL {
            get {
                return ResourceManager.GetString("CreateAccountURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employees/.
        /// </summary>
        internal static string EmployeesURL {
            get {
                return ResourceManager.GetString("EmployeesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login/.
        /// </summary>
        internal static string LoginURL {
            get {
                return ResourceManager.GetString("LoginURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materials/.
        /// </summary>
        internal static string MaterialsURL {
            get {
                return ResourceManager.GetString("MaterialsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders/.
        /// </summary>
        internal static string OrdersURL {
            get {
                return ResourceManager.GetString("OrdersURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo/.
        /// </summary>
        internal static string PhotoURL {
            get {
                return ResourceManager.GetString("PhotoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services/.
        /// </summary>
        internal static string ServicesURL {
            get {
                return ResourceManager.GetString("ServicesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token/.
        /// </summary>
        internal static string TokenURL {
            get {
                return ResourceManager.GetString("TokenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update/.
        /// </summary>
        internal static string UpdateURL {
            get {
                return ResourceManager.GetString("UpdateURL", resourceCulture);
            }
        }
    }
}
