//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFrontend.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToastDisplayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToastDisplayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFrontend.Resources.Files.ToastDisplayResources", typeof(ToastDisplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa alegeti o companie caruia ii veti fi afiliat.
        /// </summary>
        internal static string CompanyChoiceError {
            get {
                return ResourceManager.GetString("CompanyChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea serviciilor.
        /// </summary>
        internal static string CompanyServicesError {
            get {
                return ResourceManager.GetString("CompanyServicesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exista deja un cont cu aceasta adresa.
        /// </summary>
        internal static string CreateAccountError {
            get {
                return ResourceManager.GetString("CreateAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost creat cu succes.
        /// </summary>
        internal static string CreateAccountSuccess {
            get {
                return ResourceManager.GetString("CreateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toate campurile trebuie completate.
        /// </summary>
        internal static string DataMissingError {
            get {
                return ResourceManager.GetString("DataMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea datelor.
        /// </summary>
        internal static string DataUpdateFail {
            get {
                return ResourceManager.GetString("DataUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datele au fost salvate cu succes.
        /// </summary>
        internal static string DataUpdateSuccess {
            get {
                return ResourceManager.GetString("DataUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de mail nu are formatul corect.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa confirmati angajatul?.
        /// </summary>
        internal static string EmployeeConfirmation {
            get {
                return ResourceManager.GetString("EmployeeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare cont angajat.
        /// </summary>
        internal static string EmployeeConfirmationTitle {
            get {
                return ResourceManager.GetString("EmployeeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functia deja exista.
        /// </summary>
        internal static string FunctionError {
            get {
                return ResourceManager.GetString("FunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul deja exista sau datele sunt incorecte.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ati fost autentificat cu succes.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa iesiti din cont?.
        /// </summary>
        internal static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare delogare.
        /// </summary>
        internal static string LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa confirmati comanda?.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare comanda.
        /// </summary>
        internal static string OrderConfirmationTitle {
            get {
                return ResourceManager.GetString("OrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu este niciun angajat liber, va rog sa alegeti o alta data.
        /// </summary>
        internal static string OrderTimeEstimationError {
            get {
                return ResourceManager.GetString("OrderTimeEstimationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a estimat o durata aproximativa pentru serviciul ales.
        /// </summary>
        internal static string OrderTimeEstimationSuccess {
            get {
                return ResourceManager.GetString("OrderTimeEstimationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolele nu corespund.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul de telefon nu este unul valid.
        /// </summary>
        internal static string PhoneNumberError {
            get {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la plasarea comenzii.
        /// </summary>
        internal static string PlaceOrderError {
            get {
                return ResourceManager.GetString("PlaceOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda dvs a fost plasata cu succes.
        /// </summary>
        internal static string PlaceOrderSuccess {
            get {
                return ResourceManager.GetString("PlaceOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunta.
        /// </summary>
        internal static string PromptCancel {
            get {
                return ResourceManager.GetString("PromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string PromptYes {
            get {
                return ResourceManager.GetString("PromptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-ul nu a fost salvat cu succes. Incercati din nou.
        /// </summary>
        internal static string SavePhotoFail {
            get {
                return ResourceManager.GetString("SavePhotoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-ul a fost salvat cu succes.
        /// </summary>
        internal static string SavePhotoSuccess {
            get {
                return ResourceManager.GetString("SavePhotoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa adaugati serviciul {0} in cos?.
        /// </summary>
        internal static string ServiceSelected {
            get {
                return ResourceManager.GetString("ServiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectare serviciu.
        /// </summary>
        internal static string ServiceSelectedTitle {
            get {
                return ResourceManager.GetString("ServiceSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa alegeti un tip de strada.
        /// </summary>
        internal static string StreetTypeError {
            get {
                return ResourceManager.GetString("StreetTypeError", resourceCulture);
            }
        }
    }
}
