//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFrontend.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToastDisplayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToastDisplayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFrontend.Resources.Files.ToastDisplayResources", typeof(ToastDisplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa anulati comanda?.
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la anularea comenzii.
        /// </summary>
        internal static string CancelOrderError {
            get {
                return ResourceManager.GetString("CancelOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda dvs. a fost anulata.
        /// </summary>
        internal static string CancelOrderSuccess {
            get {
                return ResourceManager.GetString("CancelOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulare comanda.
        /// </summary>
        internal static string CancelOrderTitle {
            get {
                return ResourceManager.GetString("CancelOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la schimbarea timpului.
        /// </summary>
        internal static string ChangeOrderError {
            get {
                return ResourceManager.GetString("ChangeOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a trimis cu succes cererea de schimbare a timpului comenzii.
        /// </summary>
        internal static string ChangeOrderSuccess {
            get {
                return ResourceManager.GetString("ChangeOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa cereti schimbarea orei comenzii? Clientul este cel care va aproba sau refuza.
        /// </summary>
        internal static string ChangeOrderTime {
            get {
                return ResourceManager.GetString("ChangeOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schimbare ora comanda.
        /// </summary>
        internal static string ChangeOrderTimeTitle {
            get {
                return ResourceManager.GetString("ChangeOrderTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa alegeti o companie caruia ii veti fi afiliat.
        /// </summary>
        internal static string CompanyChoiceError {
            get {
                return ResourceManager.GetString("CompanyChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea serviciilor.
        /// </summary>
        internal static string CompanyServicesError {
            get {
                return ResourceManager.GetString("CompanyServicesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa confirmati schimbarea timpului comenzii?.
        /// </summary>
        internal static string ConfirmOrderTimeChangeRequest {
            get {
                return ResourceManager.GetString("ConfirmOrderTimeChangeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la schimbarea timpului.
        /// </summary>
        internal static string ConfirmOrderTimeChangeRequestError {
            get {
                return ResourceManager.GetString("ConfirmOrderTimeChangeRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda dvs a fost confirmata la noua data cu succes.
        /// </summary>
        internal static string ConfirmOrderTimeChangeRequestSuccess {
            get {
                return ResourceManager.GetString("ConfirmOrderTimeChangeRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare comanda.
        /// </summary>
        internal static string ConfirmOrderTimeChangeRequestTitle {
            get {
                return ResourceManager.GetString("ConfirmOrderTimeChangeRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exista deja un cont cu aceasta adresa.
        /// </summary>
        internal static string CreateAccountError {
            get {
                return ResourceManager.GetString("CreateAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost creat cu succes.
        /// </summary>
        internal static string CreateAccountSuccess {
            get {
                return ResourceManager.GetString("CreateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toate campurile trebuie completate.
        /// </summary>
        internal static string DataMissingError {
            get {
                return ResourceManager.GetString("DataMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea datelor.
        /// </summary>
        internal static string DataUpdateFail {
            get {
                return ResourceManager.GetString("DataUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datele au fost salvate cu succes.
        /// </summary>
        internal static string DataUpdateSuccess {
            get {
                return ResourceManager.GetString("DataUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa refuzati schimbarea timpului comenzii?.
        /// </summary>
        internal static string DeclineOrderTimeChangeRequest {
            get {
                return ResourceManager.GetString("DeclineOrderTimeChangeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la refuzarea cererii de schimbare a timpului.
        /// </summary>
        internal static string DeclineOrderTimeChangeRequestError {
            get {
                return ResourceManager.GetString("DeclineOrderTimeChangeRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a trimis refuzarea cererii.
        /// </summary>
        internal static string DeclineOrderTimeChangeRequestSuccess {
            get {
                return ResourceManager.GetString("DeclineOrderTimeChangeRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuzare comanda.
        /// </summary>
        internal static string DeclineOrderTimeChangeRequestTitle {
            get {
                return ResourceManager.GetString("DeclineOrderTimeChangeRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa amanati comenzile cu 10 minute?.
        /// </summary>
        internal static string DelayOrder {
            get {
                return ResourceManager.GetString("DelayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la amanare.
        /// </summary>
        internal static string DelayOrderError {
            get {
                return ResourceManager.GetString("DelayOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ati amanat cu succes toate comenzile din ziua de azi.
        /// </summary>
        internal static string DelayOrderSuccess {
            get {
                return ResourceManager.GetString("DelayOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amanare comenzi.
        /// </summary>
        internal static string DelayOrderTitle {
            get {
                return ResourceManager.GetString("DelayOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doriti sa descarcati un raport detaliat al performantei companiei?.
        /// </summary>
        internal static string DownloadCSVRaport {
            get {
                return ResourceManager.GetString("DownloadCSVRaport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarcare raport.
        /// </summary>
        internal static string DownloadCSVRaportTitle {
            get {
                return ResourceManager.GetString("DownloadCSVRaportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de mail nu are formatul corect.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa confirmati angajatul?.
        /// </summary>
        internal static string EmployeeConfirmation {
            get {
                return ResourceManager.GetString("EmployeeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare cont angajat.
        /// </summary>
        internal static string EmployeeConfirmationTitle {
            get {
                return ResourceManager.GetString("EmployeeConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doriti sa inregistrati finalizarea comenzii?.
        /// </summary>
        internal static string FinishOrder {
            get {
                return ResourceManager.GetString("FinishOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea statusului comenzii.
        /// </summary>
        internal static string FinishOrderError {
            get {
                return ResourceManager.GetString("FinishOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ati finalizat comanda cu succes.
        /// </summary>
        internal static string FinishOrderSuccess {
            get {
                return ResourceManager.GetString("FinishOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incheiere comanda.
        /// </summary>
        internal static string FinishOrderTitle {
            get {
                return ResourceManager.GetString("FinishOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functia deja exista.
        /// </summary>
        internal static string FunctionError {
            get {
                return ResourceManager.GetString("FunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul deja exista sau datele sunt incorecte.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ati fost autentificat cu succes.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa iesiti din cont?.
        /// </summary>
        internal static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare delogare.
        /// </summary>
        internal static string LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa confirmati comanda?.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmare comanda.
        /// </summary>
        internal static string OrderConfirmationTitle {
            get {
                return ResourceManager.GetString("OrderConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-a fost aplicat un cupon de reducere la comanda.
        /// </summary>
        internal static string OrderOfferSuccess {
            get {
                return ResourceManager.GetString("OrderOfferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu este niciun angajat liber, va rog sa alegeti o alta data.
        /// </summary>
        internal static string OrderTimeEstimationError {
            get {
                return ResourceManager.GetString("OrderTimeEstimationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a estimat o durata aproximativa pentru serviciul ales.
        /// </summary>
        internal static string OrderTimeEstimationSuccess {
            get {
                return ResourceManager.GetString("OrderTimeEstimationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se pot programa comenzi in afara orarului.
        /// </summary>
        internal static string OutOfOfficeOrderError {
            get {
                return ResourceManager.GetString("OutOfOfficeOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolele nu corespund.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se pot programa comenzi in trecut sau in ziua curenta.
        /// </summary>
        internal static string PastDateOrderError {
            get {
                return ResourceManager.GetString("PastDateOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numarul de telefon nu este unul valid.
        /// </summary>
        internal static string PhoneNumberError {
            get {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la plasarea comenzii.
        /// </summary>
        internal static string PlaceOrderError {
            get {
                return ResourceManager.GetString("PlaceOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comanda dvs a fost plasata cu succes.
        /// </summary>
        internal static string PlaceOrderSuccess {
            get {
                return ResourceManager.GetString("PlaceOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunta.
        /// </summary>
        internal static string PromptCancel {
            get {
                return ResourceManager.GetString("PromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string PromptYes {
            get {
                return ResourceManager.GetString("PromptYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-ul nu a fost salvat cu succes. Incercati din nou.
        /// </summary>
        internal static string SavePhotoFail {
            get {
                return ResourceManager.GetString("SavePhotoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-ul a fost salvat cu succes.
        /// </summary>
        internal static string SavePhotoSuccess {
            get {
                return ResourceManager.GetString("SavePhotoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa adaugati serviciul {0} in cos?.
        /// </summary>
        internal static string ServiceSelected {
            get {
                return ResourceManager.GetString("ServiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectare serviciu.
        /// </summary>
        internal static string ServiceSelectedTitle {
            get {
                return ResourceManager.GetString("ServiceSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ati rotit astazi deja. Intoarceti-va maine pentru mai multe sanse la premii.
        /// </summary>
        internal static string SpinningWheelInvalid {
            get {
                return ResourceManager.GetString("SpinningWheelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghinion! Puteti incerca maine din nou!.
        /// </summary>
        internal static string SpinningWheelNoPrize {
            get {
                return ResourceManager.GetString("SpinningWheelNoPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felicitari! Ati castigat!.
        /// </summary>
        internal static string SpinningWheelPrize {
            get {
                return ResourceManager.GetString("SpinningWheelPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca doriti sa trimiteti recenzia?.
        /// </summary>
        internal static string StarReview {
            get {
                return ResourceManager.GetString("StarReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa acordati macar o stea.
        /// </summary>
        internal static string StarReviewError {
            get {
                return ResourceManager.GetString("StarReviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a produs o eroare la salvarea comentariului.
        /// </summary>
        internal static string StarReviewFail {
            get {
                return ResourceManager.GetString("StarReviewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-a salvat comentariul cu succes.
        /// </summary>
        internal static string StarReviewSuccess {
            get {
                return ResourceManager.GetString("StarReviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvare recenzie.
        /// </summary>
        internal static string StarReviewTitle {
            get {
                return ResourceManager.GetString("StarReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuie sa alegeti un tip de strada.
        /// </summary>
        internal static string StreetTypeError {
            get {
                return ResourceManager.GetString("StreetTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu se pot programa comenzi in weekend.
        /// </summary>
        internal static string WeekendOrderError {
            get {
                return ResourceManager.GetString("WeekendOrderError", resourceCulture);
            }
        }
    }
}
